import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :health_web, HealthWebWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4002],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "u4T8fNqor+PBGXHS9mblMlZOkg9suUxoGyR5Rsn2xTbOJRHOpDk7LdEEkRB5uSl/",
  watchers: [
    asset_copy:
      {Phoenix.Copy, :watch, [[:default, :public_file]]},
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]},
    sass: {DartSass, :install_and_run, [:default, ~w(--watch)]}
  ],
  host: "http://localhost:4000"

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :health_web, HealthWebWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/health_web_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

config :health_web,
  env: config_env(),
  base_url: "http://localhost:4000/api",
  FBPOST_CRONTAB: "* * * * *",
  page_id: "106247004965721",
  access_token: "EAAGmK9PTDqQBO2swocCeQMZBVqgq9hz1BnuFtWvmG8j6OmZC9YSlJJPZADOkvvoraYIcBVEsZBvMLOJmX2rMf1cnpxFhYZA9AmjQAjBAnAVPBA0aNoCMAJonM7xCnMZCw2tW6CkSG5Y8GSeOZCvHk6TJb05UMJMMTjiWkGZCRqWINK9Il4z3DkbCxxoJGw0yztoZD"

# Enable dev routes for dashboard and mailbox
config :health_web, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
